# Site settings
title: Python Lesson Exercises
email: programmierung@ifsr.de
description: >
  Rendered exercise descriptions for the python lessons
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fsr.github.io/python-lessons/" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: fsr

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "exercises"
    values:
      layout: "post"

collections:
  exercises:
    output: true
